# Generated by Django 5.0.3 on 2024-06-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_configuracion_enviadocl'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugada',
            name='enviadoCl',
            field=models.BooleanField(default=False),
        ),
    ]
